import Head from 'next/head'
import Link from 'next/link'
import styles from './pokemon.module.css'

/**
 * @abstract 1. generate and EXOPRT all possible paths
 * @returns params containing all possibe paths, 
 *          each of which is representing one page,
 *          to be generated at buid time
 */
 export const getStaticPaths = async () => {
  const res  = await fetch('https://pokeapi.co/api/v2/pokemon?limit=200')
  const pokemon = await res.json()

  let paths = pokemon.results.map(
    (p: any) => `/pokemon/${p.name}`
  )

  return {
    paths,
    fallback: false  // goes to 404 if path not found
  }
}

/**
 * @abstract 2. create and EXPORT the props for each of the params
 * @param params generated by getStaticPaths() 
 * @returns props
 */
 export const getStaticProps = async ({ params }) => {
  const res  = await fetch(`https://pokeapi.co/api/v2/pokemon/${params.pokemon}`)
  const pokemon = await res.json()

  return {
    props: {
      pokemon
    }
  }
}

interface Props{
  pokemon: any
}

/**
 * @abstract  3. for each path with its props: create and EXPORT DEFAULT a component
 * @param props generated by getStaticProps() 
 * @returns the component /pokemon/<name>
 */
export const Pokemon = ({ pokemon }: Props) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon: {pokemon?.name}</title>
        {/* important for SEO */}
      </Head>
      <h1>I am {pokemon?.name}!</h1>
      <img width="200px" src={pokemon?.sprites.front_default} />
      <Link href="/pokemon">Take me back to the list of Pokemons</Link>
    </div>
  )
}
export default Pokemon  // pages as routes need a default export!!